name: Go
on:
  push:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.mod'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/go.yml'
env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
        with:
          args: 'run --timeout=30m'