name: Runtime-PHP
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/runtime-php.yml'
      - 'docker/php/**'
      - 'daemon/**'

jobs:
  build:
    name: Build Docker image
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod tidy

      - name: Build binary
        run: cd daemon && CGO_ENABLED=0 go build -v -trimpath

      - name: Build & Publish to Docker Registry
        uses: wuhan005/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.hub.docker.com
          repository: registry.hub.docker.com/elainaruntime/php
          tag_format: "%YYYY%_%MM%_%DD%_%H%%m%%s%"
          file: ./docker/images/php/Dockerfile
          auto_tag: true